package com.catastro.entities;
// Generated 27-abr-2015 10:16:11 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Construcciones generated by hbm2java
 */
public class Construcciones  implements java.io.Serializable {


     private long idconstrucciones;
     private Fichaindividual fichaindividual;
     private String nropisosotanomezz;
     private Date fechaconstruccion;
     private String muroColumnas;
     private String techo;
     private String piso;
     private String revistimiento;
     private String banios;
     private String instelectricsanitaria;
     private Double contruccionesdeclaradas;
     private Double construccionverificada;
     private Long uca;
     private Double porcentbiencomunlegalterreno;
     private Double porcentbiencomunlegalconstruccion;
     private Double porcentbiencomunfisicoterreno;
     private Double porcentbiencomunfisicoconstruccion;
     private Long mep;
     private Long ecs;
     private Long ecc;

    public Construcciones() {
    }

	
    public Construcciones(long idconstrucciones) {
        this.idconstrucciones = idconstrucciones;
    }
    public Construcciones(long idconstrucciones, Fichaindividual fichaindividual, String nropisosotanomezz, Date fechaconstruccion, String muroColumnas, String techo, String piso, String revistimiento, String banios, String instelectricsanitaria, Double contruccionesdeclaradas, Double construccionverificada, Long uca, Double porcentbiencomunlegalterreno, Double porcentbiencomunlegalconstruccion, Double porcentbiencomunfisicoterreno, Double porcentbiencomunfisicoconstruccion, Long mep, Long ecs, Long ecc) {
       this.idconstrucciones = idconstrucciones;
       this.fichaindividual = fichaindividual;
       this.nropisosotanomezz = nropisosotanomezz;
       this.fechaconstruccion = fechaconstruccion;
       this.muroColumnas = muroColumnas;
       this.techo = techo;
       this.piso = piso;
       this.revistimiento = revistimiento;
       this.banios = banios;
       this.instelectricsanitaria = instelectricsanitaria;
       this.contruccionesdeclaradas = contruccionesdeclaradas;
       this.construccionverificada = construccionverificada;
       this.uca = uca;
       this.porcentbiencomunlegalterreno = porcentbiencomunlegalterreno;
       this.porcentbiencomunlegalconstruccion = porcentbiencomunlegalconstruccion;
       this.porcentbiencomunfisicoterreno = porcentbiencomunfisicoterreno;
       this.porcentbiencomunfisicoconstruccion = porcentbiencomunfisicoconstruccion;
       this.mep = mep;
       this.ecs = ecs;
       this.ecc = ecc;
    }
   
    public long getIdconstrucciones() {
        return this.idconstrucciones;
    }
    
    public void setIdconstrucciones(long idconstrucciones) {
        this.idconstrucciones = idconstrucciones;
    }
    public Fichaindividual getFichaindividual() {
        return this.fichaindividual;
    }
    
    public void setFichaindividual(Fichaindividual fichaindividual) {
        this.fichaindividual = fichaindividual;
    }
    public String getNropisosotanomezz() {
        return this.nropisosotanomezz;
    }
    
    public void setNropisosotanomezz(String nropisosotanomezz) {
        this.nropisosotanomezz = nropisosotanomezz;
    }
    public Date getFechaconstruccion() {
        return this.fechaconstruccion;
    }
    
    public void setFechaconstruccion(Date fechaconstruccion) {
        this.fechaconstruccion = fechaconstruccion;
    }
    public String getMuroColumnas() {
        return this.muroColumnas;
    }
    
    public void setMuroColumnas(String muroColumnas) {
        this.muroColumnas = muroColumnas;
    }
    public String getTecho() {
        return this.techo;
    }
    
    public void setTecho(String techo) {
        this.techo = techo;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public String getRevistimiento() {
        return this.revistimiento;
    }
    
    public void setRevistimiento(String revistimiento) {
        this.revistimiento = revistimiento;
    }
    public String getBanios() {
        return this.banios;
    }
    
    public void setBanios(String banios) {
        this.banios = banios;
    }
    public String getInstelectricsanitaria() {
        return this.instelectricsanitaria;
    }
    
    public void setInstelectricsanitaria(String instelectricsanitaria) {
        this.instelectricsanitaria = instelectricsanitaria;
    }
    public Double getContruccionesdeclaradas() {
        return this.contruccionesdeclaradas;
    }
    
    public void setContruccionesdeclaradas(Double contruccionesdeclaradas) {
        this.contruccionesdeclaradas = contruccionesdeclaradas;
    }
    public Double getConstruccionverificada() {
        return this.construccionverificada;
    }
    
    public void setConstruccionverificada(Double construccionverificada) {
        this.construccionverificada = construccionverificada;
    }
    public Long getUca() {
        return this.uca;
    }
    
    public void setUca(Long uca) {
        this.uca = uca;
    }
    public Double getPorcentbiencomunlegalterreno() {
        return this.porcentbiencomunlegalterreno;
    }
    
    public void setPorcentbiencomunlegalterreno(Double porcentbiencomunlegalterreno) {
        this.porcentbiencomunlegalterreno = porcentbiencomunlegalterreno;
    }
    public Double getPorcentbiencomunlegalconstruccion() {
        return this.porcentbiencomunlegalconstruccion;
    }
    
    public void setPorcentbiencomunlegalconstruccion(Double porcentbiencomunlegalconstruccion) {
        this.porcentbiencomunlegalconstruccion = porcentbiencomunlegalconstruccion;
    }
    public Double getPorcentbiencomunfisicoterreno() {
        return this.porcentbiencomunfisicoterreno;
    }
    
    public void setPorcentbiencomunfisicoterreno(Double porcentbiencomunfisicoterreno) {
        this.porcentbiencomunfisicoterreno = porcentbiencomunfisicoterreno;
    }
    public Double getPorcentbiencomunfisicoconstruccion() {
        return this.porcentbiencomunfisicoconstruccion;
    }
    
    public void setPorcentbiencomunfisicoconstruccion(Double porcentbiencomunfisicoconstruccion) {
        this.porcentbiencomunfisicoconstruccion = porcentbiencomunfisicoconstruccion;
    }
    public Long getMep() {
        return this.mep;
    }
    
    public void setMep(Long mep) {
        this.mep = mep;
    }
    public Long getEcs() {
        return this.ecs;
    }
    
    public void setEcs(Long ecs) {
        this.ecs = ecs;
    }
    public Long getEcc() {
        return this.ecc;
    }
    
    public void setEcc(Long ecc) {
        this.ecc = ecc;
    }




}


