package com.catastro.entities;
// Generated 27-abr-2015 10:16:11 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Documento generated by hbm2java
 */
public class Documento  implements java.io.Serializable {


     private long iddocumento;
     private Fichaindividual fichaindividual;
     private String nrodocumentos;
     private Date fechadocumento;
     private Double areaautorizada;
     private String nombrenotaria;
     private Integer kardex;
     private Date fechaescriturapublica;
     private Long tiposdocumentos;

    public Documento() {
    }

	
    public Documento(long iddocumento) {
        this.iddocumento = iddocumento;
    }
    public Documento(long iddocumento, Fichaindividual fichaindividual, String nrodocumentos, Date fechadocumento, Double areaautorizada, String nombrenotaria, Integer kardex, Date fechaescriturapublica, Long tiposdocumentos) {
       this.iddocumento = iddocumento;
       this.fichaindividual = fichaindividual;
       this.nrodocumentos = nrodocumentos;
       this.fechadocumento = fechadocumento;
       this.areaautorizada = areaautorizada;
       this.nombrenotaria = nombrenotaria;
       this.kardex = kardex;
       this.fechaescriturapublica = fechaescriturapublica;
       this.tiposdocumentos = tiposdocumentos;
    }
   
    public long getIddocumento() {
        return this.iddocumento;
    }
    
    public void setIddocumento(long iddocumento) {
        this.iddocumento = iddocumento;
    }
    public Fichaindividual getFichaindividual() {
        return this.fichaindividual;
    }
    
    public void setFichaindividual(Fichaindividual fichaindividual) {
        this.fichaindividual = fichaindividual;
    }
    public String getNrodocumentos() {
        return this.nrodocumentos;
    }
    
    public void setNrodocumentos(String nrodocumentos) {
        this.nrodocumentos = nrodocumentos;
    }
    public Date getFechadocumento() {
        return this.fechadocumento;
    }
    
    public void setFechadocumento(Date fechadocumento) {
        this.fechadocumento = fechadocumento;
    }
    public Double getAreaautorizada() {
        return this.areaautorizada;
    }
    
    public void setAreaautorizada(Double areaautorizada) {
        this.areaautorizada = areaautorizada;
    }
    public String getNombrenotaria() {
        return this.nombrenotaria;
    }
    
    public void setNombrenotaria(String nombrenotaria) {
        this.nombrenotaria = nombrenotaria;
    }
    public Integer getKardex() {
        return this.kardex;
    }
    
    public void setKardex(Integer kardex) {
        this.kardex = kardex;
    }
    public Date getFechaescriturapublica() {
        return this.fechaescriturapublica;
    }
    
    public void setFechaescriturapublica(Date fechaescriturapublica) {
        this.fechaescriturapublica = fechaescriturapublica;
    }
    public Long getTiposdocumentos() {
        return this.tiposdocumentos;
    }
    
    public void setTiposdocumentos(Long tiposdocumentos) {
        this.tiposdocumentos = tiposdocumentos;
    }




}


