package com.catastro.entities;
// Generated 27-abr-2015 10:16:11 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fichaindividual generated by hbm2java
 */
public class Fichaindividual  implements java.io.Serializable {


     private long idfichaIndividual;
     private Fichacatastral fichacatastral;
     private String nrofichaLote;
     private String codcontribrentas;
     private String codpredrentas;
     private String unidacumcodpredrentas;
     private Integer condtitular;
     private Integer formaadquesicion;
     private Date fechaadquesicion;
     private Integer condespecialpredio;
     private Integer nroresolucexoneracion;
     private Double porcentaje;
     private Date fichainicio;
     private Date fechavencimiento;
     private Long evaluacionprediocatastral;
     private Double atiLotecolindante;
     private Double atiJardinaislamineto;
     private Double atiArepublica;
     private Double atiAreaintangible;
     private Long condiciondeclarante;
     private Long estadollenadofichas;
     private Long nrofamilias;
     private Long nrohabitantes;
     private Long mantenimiento;
     private Set<Obrascomplotrasinstalaciones> obrascomplotrasinstalacioneses = new HashSet<Obrascomplotrasinstalaciones>(0);
     private Set<Incrprediocatastral> incrprediocatastrals = new HashSet<Incrprediocatastral>(0);
     private Set<Construcciones> construccioneses = new HashSet<Construcciones>(0);
     private Set<Detallefichaindividual> detallefichaindividuals = new HashSet<Detallefichaindividual>(0);
     private Set<Litigantes> litiganteses = new HashSet<Litigantes>(0);
     private Set<Serviciosbasicos> serviciosbasicoses = new HashSet<Serviciosbasicos>(0);
     private Set<Domiciliofiscal> domiciliofiscals = new HashSet<Domiciliofiscal>(0);
     private Set<Documento> documentos = new HashSet<Documento>(0);

    public Fichaindividual() {
    }

	
    public Fichaindividual(long idfichaIndividual) {
        this.idfichaIndividual = idfichaIndividual;
    }
    public Fichaindividual(long idfichaIndividual, Fichacatastral fichacatastral, String nrofichaLote, String codcontribrentas, String codpredrentas, String unidacumcodpredrentas, Integer condtitular, Integer formaadquesicion, Date fechaadquesicion, Integer condespecialpredio, Integer nroresolucexoneracion, Double porcentaje, Date fichainicio, Date fechavencimiento, Long evaluacionprediocatastral, Double atiLotecolindante, Double atiJardinaislamineto, Double atiArepublica, Double atiAreaintangible, Long condiciondeclarante, Long estadollenadofichas, Long nrofamilias, Long nrohabitantes, Long mantenimiento, Set<Obrascomplotrasinstalaciones> obrascomplotrasinstalacioneses, Set<Incrprediocatastral> incrprediocatastrals, Set<Construcciones> construccioneses, Set<Detallefichaindividual> detallefichaindividuals, Set<Litigantes> litiganteses, Set<Serviciosbasicos> serviciosbasicoses, Set<Domiciliofiscal> domiciliofiscals, Set<Documento> documentos) {
       this.idfichaIndividual = idfichaIndividual;
       this.fichacatastral = fichacatastral;
       this.nrofichaLote = nrofichaLote;
       this.codcontribrentas = codcontribrentas;
       this.codpredrentas = codpredrentas;
       this.unidacumcodpredrentas = unidacumcodpredrentas;
       this.condtitular = condtitular;
       this.formaadquesicion = formaadquesicion;
       this.fechaadquesicion = fechaadquesicion;
       this.condespecialpredio = condespecialpredio;
       this.nroresolucexoneracion = nroresolucexoneracion;
       this.porcentaje = porcentaje;
       this.fichainicio = fichainicio;
       this.fechavencimiento = fechavencimiento;
       this.evaluacionprediocatastral = evaluacionprediocatastral;
       this.atiLotecolindante = atiLotecolindante;
       this.atiJardinaislamineto = atiJardinaislamineto;
       this.atiArepublica = atiArepublica;
       this.atiAreaintangible = atiAreaintangible;
       this.condiciondeclarante = condiciondeclarante;
       this.estadollenadofichas = estadollenadofichas;
       this.nrofamilias = nrofamilias;
       this.nrohabitantes = nrohabitantes;
       this.mantenimiento = mantenimiento;
       this.obrascomplotrasinstalacioneses = obrascomplotrasinstalacioneses;
       this.incrprediocatastrals = incrprediocatastrals;
       this.construccioneses = construccioneses;
       this.detallefichaindividuals = detallefichaindividuals;
       this.litiganteses = litiganteses;
       this.serviciosbasicoses = serviciosbasicoses;
       this.domiciliofiscals = domiciliofiscals;
       this.documentos = documentos;
    }
   
    public long getIdfichaIndividual() {
        return this.idfichaIndividual;
    }
    
    public void setIdfichaIndividual(long idfichaIndividual) {
        this.idfichaIndividual = idfichaIndividual;
    }
    public Fichacatastral getFichacatastral() {
        return this.fichacatastral;
    }
    
    public void setFichacatastral(Fichacatastral fichacatastral) {
        this.fichacatastral = fichacatastral;
    }
    public String getNrofichaLote() {
        return this.nrofichaLote;
    }
    
    public void setNrofichaLote(String nrofichaLote) {
        this.nrofichaLote = nrofichaLote;
    }
    public String getCodcontribrentas() {
        return this.codcontribrentas;
    }
    
    public void setCodcontribrentas(String codcontribrentas) {
        this.codcontribrentas = codcontribrentas;
    }
    public String getCodpredrentas() {
        return this.codpredrentas;
    }
    
    public void setCodpredrentas(String codpredrentas) {
        this.codpredrentas = codpredrentas;
    }
    public String getUnidacumcodpredrentas() {
        return this.unidacumcodpredrentas;
    }
    
    public void setUnidacumcodpredrentas(String unidacumcodpredrentas) {
        this.unidacumcodpredrentas = unidacumcodpredrentas;
    }
    public Integer getCondtitular() {
        return this.condtitular;
    }
    
    public void setCondtitular(Integer condtitular) {
        this.condtitular = condtitular;
    }
    public Integer getFormaadquesicion() {
        return this.formaadquesicion;
    }
    
    public void setFormaadquesicion(Integer formaadquesicion) {
        this.formaadquesicion = formaadquesicion;
    }
    public Date getFechaadquesicion() {
        return this.fechaadquesicion;
    }
    
    public void setFechaadquesicion(Date fechaadquesicion) {
        this.fechaadquesicion = fechaadquesicion;
    }
    public Integer getCondespecialpredio() {
        return this.condespecialpredio;
    }
    
    public void setCondespecialpredio(Integer condespecialpredio) {
        this.condespecialpredio = condespecialpredio;
    }
    public Integer getNroresolucexoneracion() {
        return this.nroresolucexoneracion;
    }
    
    public void setNroresolucexoneracion(Integer nroresolucexoneracion) {
        this.nroresolucexoneracion = nroresolucexoneracion;
    }
    public Double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Date getFichainicio() {
        return this.fichainicio;
    }
    
    public void setFichainicio(Date fichainicio) {
        this.fichainicio = fichainicio;
    }
    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    
    public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }
    public Long getEvaluacionprediocatastral() {
        return this.evaluacionprediocatastral;
    }
    
    public void setEvaluacionprediocatastral(Long evaluacionprediocatastral) {
        this.evaluacionprediocatastral = evaluacionprediocatastral;
    }
    public Double getAtiLotecolindante() {
        return this.atiLotecolindante;
    }
    
    public void setAtiLotecolindante(Double atiLotecolindante) {
        this.atiLotecolindante = atiLotecolindante;
    }
    public Double getAtiJardinaislamineto() {
        return this.atiJardinaislamineto;
    }
    
    public void setAtiJardinaislamineto(Double atiJardinaislamineto) {
        this.atiJardinaislamineto = atiJardinaislamineto;
    }
    public Double getAtiArepublica() {
        return this.atiArepublica;
    }
    
    public void setAtiArepublica(Double atiArepublica) {
        this.atiArepublica = atiArepublica;
    }
    public Double getAtiAreaintangible() {
        return this.atiAreaintangible;
    }
    
    public void setAtiAreaintangible(Double atiAreaintangible) {
        this.atiAreaintangible = atiAreaintangible;
    }
    public Long getCondiciondeclarante() {
        return this.condiciondeclarante;
    }
    
    public void setCondiciondeclarante(Long condiciondeclarante) {
        this.condiciondeclarante = condiciondeclarante;
    }
    public Long getEstadollenadofichas() {
        return this.estadollenadofichas;
    }
    
    public void setEstadollenadofichas(Long estadollenadofichas) {
        this.estadollenadofichas = estadollenadofichas;
    }
    public Long getNrofamilias() {
        return this.nrofamilias;
    }
    
    public void setNrofamilias(Long nrofamilias) {
        this.nrofamilias = nrofamilias;
    }
    public Long getNrohabitantes() {
        return this.nrohabitantes;
    }
    
    public void setNrohabitantes(Long nrohabitantes) {
        this.nrohabitantes = nrohabitantes;
    }
    public Long getMantenimiento() {
        return this.mantenimiento;
    }
    
    public void setMantenimiento(Long mantenimiento) {
        this.mantenimiento = mantenimiento;
    }
    public Set<Obrascomplotrasinstalaciones> getObrascomplotrasinstalacioneses() {
        return this.obrascomplotrasinstalacioneses;
    }
    
    public void setObrascomplotrasinstalacioneses(Set<Obrascomplotrasinstalaciones> obrascomplotrasinstalacioneses) {
        this.obrascomplotrasinstalacioneses = obrascomplotrasinstalacioneses;
    }
    public Set<Incrprediocatastral> getIncrprediocatastrals() {
        return this.incrprediocatastrals;
    }
    
    public void setIncrprediocatastrals(Set<Incrprediocatastral> incrprediocatastrals) {
        this.incrprediocatastrals = incrprediocatastrals;
    }
    public Set<Construcciones> getConstruccioneses() {
        return this.construccioneses;
    }
    
    public void setConstruccioneses(Set<Construcciones> construccioneses) {
        this.construccioneses = construccioneses;
    }
    public Set<Detallefichaindividual> getDetallefichaindividuals() {
        return this.detallefichaindividuals;
    }
    
    public void setDetallefichaindividuals(Set<Detallefichaindividual> detallefichaindividuals) {
        this.detallefichaindividuals = detallefichaindividuals;
    }
    public Set<Litigantes> getLitiganteses() {
        return this.litiganteses;
    }
    
    public void setLitiganteses(Set<Litigantes> litiganteses) {
        this.litiganteses = litiganteses;
    }
    public Set<Serviciosbasicos> getServiciosbasicoses() {
        return this.serviciosbasicoses;
    }
    
    public void setServiciosbasicoses(Set<Serviciosbasicos> serviciosbasicoses) {
        this.serviciosbasicoses = serviciosbasicoses;
    }
    public Set<Domiciliofiscal> getDomiciliofiscals() {
        return this.domiciliofiscals;
    }
    
    public void setDomiciliofiscals(Set<Domiciliofiscal> domiciliofiscals) {
        this.domiciliofiscals = domiciliofiscals;
    }
    public Set<Documento> getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set<Documento> documentos) {
        this.documentos = documentos;
    }




}


