package com.catastro.entities;
// Generated 27-abr-2015 10:16:11 by Hibernate Tools 3.6.0



/**
 * Litigantes generated by hbm2java
 */
public class Litigantes  implements java.io.Serializable {


     private long idlitigantes;
     private Fichaindividual fichaindividual;
     private String nrodocumento;
     private String codigocontribuyente;
     private String tipodocumento;
     private String apellidos;
     private String nombres;

    public Litigantes() {
    }

	
    public Litigantes(long idlitigantes) {
        this.idlitigantes = idlitigantes;
    }
    public Litigantes(long idlitigantes, Fichaindividual fichaindividual, String nrodocumento, String codigocontribuyente, String tipodocumento, String apellidos, String nombres) {
       this.idlitigantes = idlitigantes;
       this.fichaindividual = fichaindividual;
       this.nrodocumento = nrodocumento;
       this.codigocontribuyente = codigocontribuyente;
       this.tipodocumento = tipodocumento;
       this.apellidos = apellidos;
       this.nombres = nombres;
    }
   
    public long getIdlitigantes() {
        return this.idlitigantes;
    }
    
    public void setIdlitigantes(long idlitigantes) {
        this.idlitigantes = idlitigantes;
    }
    public Fichaindividual getFichaindividual() {
        return this.fichaindividual;
    }
    
    public void setFichaindividual(Fichaindividual fichaindividual) {
        this.fichaindividual = fichaindividual;
    }
    public String getNrodocumento() {
        return this.nrodocumento;
    }
    
    public void setNrodocumento(String nrodocumento) {
        this.nrodocumento = nrodocumento;
    }
    public String getCodigocontribuyente() {
        return this.codigocontribuyente;
    }
    
    public void setCodigocontribuyente(String codigocontribuyente) {
        this.codigocontribuyente = codigocontribuyente;
    }
    public String getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(String tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }




}


