package com.catastro.entities;
// Generated 27-abr-2015 10:16:11 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ubigeo generated by hbm2java
 */
public class Ubigeo  implements java.io.Serializable {


     private long idubigeo;
     private String nombreDepartamento;
     private String nombreProvincia;
     private String nombreDistrito;
     private Integer codigoDepartamento;
     private Integer codigoProvincia;
     private Integer codigoDistrito;
     private Set<Domiciliofiscal> domiciliofiscals = new HashSet<Domiciliofiscal>(0);

    public Ubigeo() {
    }

	
    public Ubigeo(long idubigeo) {
        this.idubigeo = idubigeo;
    }
    public Ubigeo(long idubigeo, String nombreDepartamento, String nombreProvincia, String nombreDistrito, Integer codigoDepartamento, Integer codigoProvincia, Integer codigoDistrito, Set<Domiciliofiscal> domiciliofiscals) {
       this.idubigeo = idubigeo;
       this.nombreDepartamento = nombreDepartamento;
       this.nombreProvincia = nombreProvincia;
       this.nombreDistrito = nombreDistrito;
       this.codigoDepartamento = codigoDepartamento;
       this.codigoProvincia = codigoProvincia;
       this.codigoDistrito = codigoDistrito;
       this.domiciliofiscals = domiciliofiscals;
    }
   
    public long getIdubigeo() {
        return this.idubigeo;
    }
    
    public void setIdubigeo(long idubigeo) {
        this.idubigeo = idubigeo;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public String getNombreProvincia() {
        return this.nombreProvincia;
    }
    
    public void setNombreProvincia(String nombreProvincia) {
        this.nombreProvincia = nombreProvincia;
    }
    public String getNombreDistrito() {
        return this.nombreDistrito;
    }
    
    public void setNombreDistrito(String nombreDistrito) {
        this.nombreDistrito = nombreDistrito;
    }
    public Integer getCodigoDepartamento() {
        return this.codigoDepartamento;
    }
    
    public void setCodigoDepartamento(Integer codigoDepartamento) {
        this.codigoDepartamento = codigoDepartamento;
    }
    public Integer getCodigoProvincia() {
        return this.codigoProvincia;
    }
    
    public void setCodigoProvincia(Integer codigoProvincia) {
        this.codigoProvincia = codigoProvincia;
    }
    public Integer getCodigoDistrito() {
        return this.codigoDistrito;
    }
    
    public void setCodigoDistrito(Integer codigoDistrito) {
        this.codigoDistrito = codigoDistrito;
    }
    public Set<Domiciliofiscal> getDomiciliofiscals() {
        return this.domiciliofiscals;
    }
    
    public void setDomiciliofiscals(Set<Domiciliofiscal> domiciliofiscals) {
        this.domiciliofiscals = domiciliofiscals;
    }




}


